pipeline:
  name: release
  jobs:
    - name: release
      if: |
        "${{ release }}" != ''
      enabled: true
      steps:
        - name: check for ~/.m2/prometheus.settings.xml
          run: if [ -f "~/.m2/verifyica.settings.xml" ]; then echo "~/.m2/verifyica.settings.xml required, exiting" && exit 1; fi
        - name: change version
          run: |
            ./mvnw -B versions:set -DnewVersion="${{ release }}" -DprocessAllModules >> /dev/null
            rm -Rf $(find . -name "*versionsBackup")
        - name: build & verify
          run: ./mvnw -B clean verify
        - name: build & deploy
          run: ./mvnw -s ~/.m2/verifyica.settings.xml -P release clean deploy
        - name: commit version
          run: |
            git add -u
            git commit -s -m "release-${{ release }}"
        - name: tag version
          run: |
            git tag "${{ release }}"
            git push --tags
        - name: checkout & push release branch
          run: |
            git checkout -b "release-${{ release }}"
            git push --set-upstream origin "release-${{ release }}"
        - name: checkout main
          run: git checkout main
        - name: change version
          run: |
            ./mvnw -B versions:set -DnewVersion="${{ release }}-post" -DprocessAllModules >> /dev/null
            rm -Rf $(find . -name "*versionsBackup")
        - name: commit version
          run: |
            git add -u
            git commit -s -m "Prepare for development"
        - name: git push
          run: git push
    - name: error
      if: |
        "${{ release }}" == ''
      steps:
        - name: error
          run: |
            --print "release" variable is required
            exit 1
